### ISSUE TITLE
Privacy Provider and Moodle compatibility

### ISSUE THREAD

**Issue by pauldamiani** [netspotau/moodle-mod_teambuilder#10]
Hi Adam,
I am trying to use this plugin on a Moodle 3.5 site but due to your recent changes to the minimum required Moodle version, I can no longer use the plugin.
The privacy provider requirements are compatible with Moodle versions down to 3.5, is it possible for you to lower the minimum required Moodle version to accept 3.5? Or make 3X_STABLE branches for older Moodle versions.

Regards,
Paul

**Comment by aolley** [comment]
There already was one - MOODLE_33_STABLE. I've pushed MOODLE_36_STABLE as well - but it points at the same commit - as the changes since those are the ones for 3.7.
