### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinism** [netspotau/moodle-mod_teambuilder#7]
Can this strings be translated? Thanks
http://imgur.com/a/4TlwI

**Comment by aolley** [comment]
I've just pushed up a couple commits that cover most of those.
I won't push a release through to moodle.org until I've covered all the strings and more thoroughly tested the changes.

**Comment by aolley** [comment]
I've just updated the editing interface to have its strings translatable as well. I think that's all of them. Lemme know if I missed anything.
