### ISSUE TITLE
Question does not save

### ISSUE THREAD

**Issue by rbonatuvic** [netspotau/moodle-mod_teambuilder#8]
Firefox, Chrome, Moodle 3.4, php 7
Create a question and answers. Click 'Add New Question'. Question is displayed on page.
Javascript error is 'questionView.find(...).sortable is not a function' in addNewQuestion (editview.js).
No 'Saving...' nor 'Saved! message is displayed.
Click 'Save Questionnaire' and nothing is saved.
Javascript error is 'question is undefined' in saveQuestionnaire. That is, '$(this).data("question")' does not return the question.
I think this is because '$(this)' is not referring to the correct target.

**Comment by aolley** [comment]
Wow, this is actually quite broken isn't it. I'm actively working on fixing this now...

**Comment by aolley** [comment]
The latest commit on master should fix this now.

I've bumped the version.php to require Moodle 3.3 simply as I'm not guaranteeing any support for prior versions at this point.
